### ISSUE TITLE
multi recipient direct message - life after irslackd disconnect

### ISSUE THREAD

**Issue by jcolson** [adsr/irslackd#83]
**Description**
currently, once irslackd disconnects from slack, the multi-recipient direct message channels don't survive.  what would it entail to allow those conversations to live through restarts?

**Comment by fancypantalons** [comment]
You know, one option, which... maybe is a bit ugly... is irslackd could parse the channel name to split out the nicklist (since it's baked into the channel name, anyway), and then trigger a "conversation.open" call to re-join the group chat properly.

This could be done up in onIrcJoin.  That function could check the format of the channel name, and if it doesn't started with "#mpdm", pass control to onIrcJoinOne as it does currently.

If it *does* start with #mpdm, split the channel name up, yank out the nicks, and call "conversation.open" and then let the server response configure the rest of the channel setup.  And naturally, if any of the nicks is no longer valid, just return and do nothing.

Thoughts?

**Comment by adsr** [comment]
We might try removing this line in slack-init.js:

https://github.com/adsr/irslackd/blob/990cfe3ac1dce9c643a8dd492be3381c5782dec4/lib/slack-init.js#L14

I can't remember why I did this... There may be some special treatment required for mpdms but in general I don't see why we can't let them get hydrated the same way other conversations are hydrated.

**Comment by fancypantalons** [comment]
Yeah, my initiate belief reading the code--and I need to go read the code in much greater detail to confirm--is that the basic API interactions necessary to hydrate a mpdms are different from those used to hydrate a regular channel... 

But obviously that doesn't preclude writing a separate codepath for dealing with mpdms.  Maybe I'll poke around at this over the next couple days, seems like an easy enough add.

**Comment by adsr** [comment]
Added support in 76b0076. Feel free to re-open or file a new issue if you find any bugs.
