### ISSUE TITLE
Support creating group chats with the @slack bot

### ISSUE THREAD

**Issue by fancypantalons** [adsr/irslackd#94]
I wanted to throw this idea out before I build it, just in case you've already got a solve on your radar.
To me the big remaining piece of missing functionality in the bridge (which, by the way, is absolutely fantastic, really nice work and thanks to everyone involved for their efforts!) is initiating group chats... which.. I'm pretty sure isn't possible yet, though maybe I've missed something profound...

Anyway, even if we added special handling for turning joins to #mpdm channels into opening MPIMs, it'd be enormously cumbersome.

Instead, I'm considering something like:

`/msg @slack mpdm foo bar baz`

This would initiate the group chat and then force join the IRC client to the #mpdm channel.

Thoughts?

If this looks reasonable, and you don't already have a solve in mind, I'm happy taking a run at a prototype implementation.

**Comment by adsr** [comment]
Hi @fancypantalons. Glad you're finding it useful. Your idea sounds good to me.

We might receive an `mpim_open` event after calling `conversations.open` which would take care of joining the mpdm channel. (On further inspection it looks like `mpim_open` may have been replaced by `group_open` which irslackd does not currently handle? Strangely mpdms seem to be working in my setup still, hmm...)

One other point: Despite there being nothing channel-specific about opening a mpdm, you may find it easier/cleaner to reuse the existing `@slack ...` pattern instead of building out handling for `/msg @slack`.

**Comment by fancypantalons** [comment]
Absolutely my expectation was to use the existing pattern, I just apparently forgot how that worked...

Cool, I'll throw together a prototype!

**Comment by fancypantalons** [comment]
Alright, 54d07cf represents the proposed change.  You were absolutely right, it was dead simple... calling conversation.open is enough to trigger the channel creation and force join.

Take a look and let me know if you have any comments!

**Comment by adsr** [comment]
Merged in bb688ad33bee7396fb84e6048b8418742f4f60fd with a few tiny changes. (I missed your EDIT. Sorry about that.) Feel free to submit a PR if you see anything else. Thanks @fancypantalons.
